import {
  PROMPT_SECTIONS,
  type PromptEngineerOutput,
  type PromptSection,
} from '../agents/definitions/prompt-engineer.agent.js';

/**
 * The obligations the generated prompt places on the coding agent.
 *
 * These are appended by the platform rather than written by the model, so every
 * exported prompt carries them verbatim whatever the model decided to say.
 */
export const CODEX_EXECUTION_RULES = `
## EXECUTION RULES (mandatory)

1. Analyse the repository before writing code. State what you found.
2. Produce a written plan and follow it. Update it when reality disagrees.
3. Implement in phases. Each phase must leave the build compiling.
4. Run the test suite after each phase. Do not proceed on a red build.
5. Fix the errors you introduce. Do not work around them by deleting tests.
6. Never invent an API, SDK, endpoint or library that you have not verified
   exists. If a capability is missing, stop and say so.
7. Leave no critical TODO. A TODO is acceptable only for an explicitly
   out-of-scope item, and it must be listed in the README.
8. Keep the code compilable and the repository in a runnable state at all times.
9. Document non-obvious decisions in the code or in docs/, briefly.
10. Deliver a complete README: what it is, how to install, run, test and build.

## WHAT "DONE" MEANS

- The application builds from a clean checkout.
- The documented run command starts it.
- The test suite passes.
- Every acceptance criterion above is demonstrably met.
- Nothing in the repository contains a secret, a token or a password.
`.trim();

const SECTION_TITLES: Record<PromptSection, string> = {
  PROJECT_CONTEXT: 'PROJECT CONTEXT',
  BUSINESS_OBJECTIVE: 'BUSINESS OBJECTIVE',
  TARGET_USERS: 'TARGET USERS',
  MVP: 'MVP',
  TECHNICAL_ARCHITECTURE: 'TECHNICAL ARCHITECTURE',
  DATA_MODEL: 'DATA MODEL',
  API: 'API',
  UI: 'UI',
  SECURITY: 'SECURITY',
  PRIVACY: 'PRIVACY',
  MONETIZATION: 'MONETIZATION',
  ANALYTICS: 'ANALYTICS',
  TESTING: 'TESTING',
  ACCEPTANCE_CRITERIA: 'ACCEPTANCE CRITERIA',
  IMPLEMENTATION_PLAN: 'IMPLEMENTATION PLAN',
  DELIVERABLES: 'DELIVERABLES',
};

export function renderCodexPromptMarkdown(
  output: PromptEngineerOutput,
  meta: { generatedAt: Date; opportunityTitle: string; synthetic: boolean },
): string {
  const lines: string[] = [];
  const push = (...values: string[]) => lines.push(...values);

  push(`# Build prompt — ${output.projectName}`, '');
  push(
    'You are a senior software engineer working autonomously in a code',
    'generation agent. Build the application specified below, end to end.',
    '',
  );

  if (meta.synthetic) {
    push(
      '> **Warning:** generated with the offline mock provider. The sections',
      '> below are placeholders, not a real specification.',
      '',
    );
  }

  push('## STACK', '');
  push(`- **Platform:** ${output.stack.platform}`);
  push(`- **Language:** ${output.stack.language}`);
  push(`- **Frameworks:** ${output.stack.frameworks.join(', ') || 'implementer choice'}`);
  push(`- **Database:** ${output.stack.database}`);
  push(`- **Infrastructure:** ${output.stack.infrastructure}`);
  push('');

  push('## REPOSITORY STRUCTURE', '', '```');
  for (const entry of output.repositoryLayout) push(entry);
  push('```', '');

  for (const section of PROMPT_SECTIONS) {
    push(`## ${SECTION_TITLES[section]}`, '', output.sections[section], '');
  }

  push(CODEX_EXECUTION_RULES, '');
  push('---', '');
  push(
    `_Generated by AI App Factory on ${meta.generatedAt.toISOString()} from the PRD for ` +
      `"${meta.opportunityTitle}"._`,
  );

  return lines.join('\n');
}

/** Rough token count, used to warn when a prompt is getting unwieldy. */
export function estimatePromptTokens(markdown: string): number {
  return Math.ceil(markdown.length / 4);
}
